"""Downloads the Google Fonts woff2 files SOMA uses into public/fonts and writes
public/fonts/fonts.css. Re-run only when the font list in FAMILIES changes."""
import re, os, urllib.request
from collections import OrderedDict

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
FAMILIES = [
    "Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700;9..144,800",
    "Nunito:wght@400;500;600;700;800",
    "Baloo+2:wght@400;600;800",
    "JetBrains+Mono:wght@400;500",
]
URL = "https://fonts.googleapis.com/css2?" + "&".join("family=" + f for f in FAMILIES) + "&display=swap"
SUBSETS = ("latin", "latin-ext")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "frontend", "public", "fonts")


def get(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()


def main():
    os.makedirs(OUT, exist_ok=True)
    css = get(URL).decode()
    faces = OrderedDict()  # (family, subset) -> {url, weights, range}
    for subset, block in re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        entry = faces.setdefault((family, subset), {
            "url": re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1),
            "range": re.search(r"unicode-range: ([^;]+);", block).group(1),
            "weights": [],
        })
        entry["weights"].append(int(re.search(r"font-weight: (\d+)", block).group(1)))

    out = ["/* Self-hosted webfonts. Generated by scripts/fetch-fonts.py — do not edit by hand. */"]
    for (family, subset), e in faces.items():
        name = "%s-%s.woff2" % (family.lower().replace(" ", "-"), subset)
        data = get(e["url"])
        with open(os.path.join(OUT, name), "wb") as fh:
            fh.write(data)
        print("%-32s %6.1f KB" % (name, len(data) / 1024))
        lo, hi = min(e["weights"]), max(e["weights"])
        weight = str(lo) if lo == hi else "%d %d" % (lo, hi)
        out.append("\n".join([
            "@font-face {",
            "  font-family: '%s';" % family,
            "  font-style: normal;",
            "  font-weight: %s;" % weight,
            # `block` (not `swap`): with the preloads in index.html the file lands in
            # a few ms, and blocking means text never paints in the fallback face
            # first — that swap was the flash of wrong font on first load.
            "  font-display: block;",
            "  src: url(/fonts/%s) format('woff2');" % name,
            "  unicode-range: %s;" % e["range"],
            "}",
        ]))

    with open(os.path.join(OUT, "fonts.css"), "w") as fh:
        fh.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
